### ISSUE TITLE
HTTP requests "hang forever"

### ISSUE THREAD

**Issue by fgr** [vlingo/vlingo-helloworld#1]
Any access to the HTTP resources freezes/blocks forever:

`curl -i -X GET http://localhost:8080/hello` (as well as using a browser) does not respond/return. The server log (see below) does not indicate any activity when a request is made.

What's interesting (at least to me) is that on Linux and macOS the server socket uses IPv6 only. Running `netstat -tlpn | grep LISTEN` on Linux and `sudo lsof -PiTCP -sTCP:LISTEN` on macOS gives:

> tcp6       0      0 :::8080                 :::*                    LISTEN      2292/java

Using IPv6 addresses for the HTTP requests (like `curl -i -X GET http://[::1]:8080/hello`) leads to the same result (no response).

Is there any way to enable debug output for `io.vlingo.http.resource.Server`?

The server was started using `java -jar target/vlingo-helloworld-withdeps.jar 8080`. Here is the server log:

> 13:08:18.532 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger -  io.vlingo.hello.infra.persistence.QueriesActor - vlingo/actors: Generating proxy for main: io.vlingo.hello.infra.persistence.Queries
13:08:20.549 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Probe interval: 3 Probe timeout: 2
13:08:20.583 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Probe interval: 3 Probe timeout: 2
13:08:20.586 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Probe interval: 3 Probe timeout: 2
13:08:20.591 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Probe interval: 3 Probe timeout: 2
13:08:20.596 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Probe interval: 3 Probe timeout: 2
13:08:20.597 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Probe interval: 3 Probe timeout: 2
13:08:20.599 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Probe interval: 3 Probe timeout: 2
13:08:20.600 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Probe interval: 3 Probe timeout: 2
13:08:20.600 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Probe interval: 3 Probe timeout: 2
13:08:20.602 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Probe interval: 3 Probe timeout: 2
13:08:20.629 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - ServerRequestResponseChannelActor: OPENING PORT: 8080
13:08:20.644 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Server vlingo-http-server is listening on port: 8080 started in 208 ms
13:08:20.645 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Resource: Greeting Resource
13:08:20.646 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=0, method=PATCH, uri=/greetings/{greetingId}/message, to=dynamic1(String greetingId)
13:08:20.647 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=1, method=PATCH, uri=/greetings/{greetingId}/description, to=dynamic2(String greetingId)
13:08:20.647 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=2, method=GET, uri=/greetings/{greetingId}, to=dynamic3(String greetingId)
13:08:20.648 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=3, method=POST, uri=/greetings, to=dynamic4()
13:08:20.649 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=4, method=GET, uri=/greetings, to=dynamic5()
13:08:20.649 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Resource: Hello Resource
13:08:20.650 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=0, method=GET, uri=/hello/{whom}, to=dynamic1(String whom)
13:08:20.650 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=1, method=GET, uri=/hello, to=dynamic2()
13:08:20.664 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - ============================================
13:08:20.665 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - Started hello-world service on port 8080
13:08:20.666 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - ============================================

**Comment by VaughnVernon** [comment]
@fgr Thanks! Is the hang only on Linux? If so we are aware of the JDK/JRE problem (re)introduced with 1.8 and trying to find a fix. Netty had the same issue and we may be able to use their fix.

**Comment by fgr** [comment]
@VaughnVernon Thanks for your prompt reply!

> Is the hang only on Linux?

No, it hangs on Linux and macOS when I use a IPv4 address (localhost or 127.0.0.1). It works fine on macOS with Java 1.8 with an IPv6 address. Sorry for the confusion.

BTW: On macOS with an IPv4 address, when I abort the client (Ctrl-c for curl, close browser tab), it get at least a server message:

> 14:45:06.333 [pool-2-thread-1] INFO  io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Client channel didn't close normally, but is probably already closed.

I did not observe such a message on Linux though.

**Comment by fgr** [comment]
Did more tests on MacOS: It seems to me that only the first request (after the server was started) gets a proper response (200). Any additional request blocks as described above...

**Comment by fgr** [comment]
Did some more testing on macOS: The requests do not actually block, their handling/reply just takes a long time (the response time grows exponentially (how apt in these days) with every request), but they are handles correctly (200 OK).

> $ time curl -i -X GET http://localhost:18080/hello
real	0m5.594s
user	0m0.004s
sys	0m0.009s
$ time curl -i -X GET http://localhost:18080/hello
real	0m27.211s
user	0m0.004s
sys	0m0.008s
$ time curl -i -X GET http://localhost:18080/hello
real	4m42.927s
user	0m0.007s
sys	0m0.020s
$ time curl -i -X GET http://localhost:18080/hello
real	52m40.278s
user	0m0.016s
sys	0m0.046s

And just for clarification: As you can see, IPv4 requests work fine. So my initial suspicion that IPv6 might cause the observed blockage was apparently unjustified.

**Comment by VaughnVernon** [comment]
@fgr Thanks for sticking with this! I am going to cross link this with the original Issue. You can see by following the link where the problem takes place. This is the exact same behavior as was seen with Netty, but only on Linux. Also I develop on Mac and I never see the problem.

https://github.com/vlingo/vlingo-wire/issues/28

**Comment by VaughnVernon** [comment]
@fgr I had to reread the following a few times, and I am still not sure what you mean.

> As you can see, IPv4 requests work fine. So my initial suspicion that IPv6 might cause the observed blockage was apparently unjustified.

This seems to be a contradiction. First, I don't know why you would conclude that IPv4 works fine if the response is exponentially slower on each subsequent request. And as far as I understood from a previous comment, IPv6 worked fine.

> It works fine on macOS with Java 1.8 with an IPv6 address

Did you transpose IPv4 and IPv6 in your latest comment? Or maybe you can clarify.

I have done tests with both IPv4 and IPv6. They both work and have zero degradation in performance as I run them repeatedly.

**IPv6**
```
$ time curl -i -X GET http://[::1]:8080/hello
HTTP/1.1 200 OK
Content-Length: 13

Hello, World!
real	0m0.034s
user	0m0.006s
sys	0m0.008s

$ time curl -i -X GET http://[::1]:8080/hello
HTTP/1.1 200 OK
Content-Length: 13

Hello, World!
real	0m0.034s
user	0m0.006s
sys	0m0.009s

$ time curl -i -X GET http://[::1]:8080/hello
HTTP/1.1 200 OK
Content-Length: 13

Hello, World!
real	0m0.035s
user	0m0.006s
sys	0m0.008s

$ time curl -i -X GET http://[::1]:8080/hello
HTTP/1.1 200 OK
Content-Length: 13

Hello, World!
real	0m0.030s
user	0m0.007s
sys	0m0.007s
```

**IPv4**
```
$ time curl -i -X GET http://localhost:8080/hello
HTTP/1.1 200 OK
Content-Length: 13

Hello, World!
real	0m0.034s
user	0m0.007s
sys	0m0.009s

$ time curl -i -X GET http://localhost:8080/hello
HTTP/1.1 200 OK
Content-Length: 13

Hello, World!
real	0m0.037s
user	0m0.007s
sys	0m0.009s

$ time curl -i -X GET http://localhost:8080/hello
HTTP/1.1 200 OK
Content-Length: 13

Hello, World!
real	0m0.029s
user	0m0.007s
sys	0m0.007s

$ time curl -i -X GET http://localhost:8080/hello
HTTP/1.1 200 OK
Content-Length: 13

Hello, World!
real	0m0.026s
user	0m0.006s
sys	0m0.005s
```

I have never seen any issues with MacOS and Java IP. We have also had no such reports before your. Currently Linux is a problem, and I think I have a fix for it.

**Comment by fgr** [comment]
@VaughnVernon Sorry, I phrased my IPv4 statement completely wrong. What I wanted to say is that even though the socket appears to be an IPv6 one, using IPv4 works "fine" with regards to the IPv4 client being able to connect to the server and send data to and receive data from it. 

Sorry for the wrong wording, I did not imply to say that with IPv4 the Hello World setup works fine in general. The slow response problem is still there with IPv4 on macOS and Linux.

Thanks for cross-referencing the original issue, @VaughnVernon. I shall investigate further...

**Comment by VaughnVernon** [comment]
Was previously fixed by increasing the socket channel probe interval. However, it is now recommended to use `Server.startWithAgent(...)` for cross OS type support.

See:
https://github.com/vlingo/vlingo-helloworld/blob/8b1543f40dea265ffc3e1ac0f77a2c8508f309c7/src/main/java/io/vlingo/hello/Bootstrap.java#L67

**Comment by VaughnVernon** [comment]
Was previously fixed by increasing the socket channel probe interval. However, it is now recommended to use `Server.startWithAgent(...)` for cross OS type support.

See:
https://github.com/vlingo/vlingo-helloworld/blob/8b1543f40dea265ffc3e1ac0f77a2c8508f309c7/src/main/java/io/vlingo/hello/Bootstrap.java#L67
