### ISSUE TITLE
XoomInitializer is missing

### ISSUE THREAD

**Issue by jakzal** [vlingo/vlingo-helloworld#4]
io.vlingo.hello.XoomInitializer class wasn't added to the project but is referenced in https://github.com/vlingo/vlingo-helloworld/commit/fbfa381a3fdcbd3c246b2e3707929bca9ed038d4

/cc @danilo-ambrosio

**Comment by jakzal** [comment]
Just realised the class is generated. Nevermind :)

**Comment by VaughnVernon** [comment]
😃
