### ISSUE TITLE
 No registered default CompletesEventuallyProvider

### ISSUE THREAD

**Issue by awsl-dbq** [vlingo/vlingo-helloworld#5]
```
 curl -i -X GET http://localhost:18080/hello

HTTP/1.1 400 Bad Request
Content-Length: 50

No registered default CompletesEventuallyProvider.%  
```

```
➜  vlingo-helloworld git:(master) ✗ java -jar target/vlingo-helloworld-withdeps.jar
=========================
service: hello-world.
=========================
Unable to read properties.
hello-world: Command line does not provide a valid port; defaulting to: 18080
15:34:27.890 [main] INFO  i.v.w.f.b.n.s.NettyServerChannelActor - Netty server running on Linux
15:34:27.892 [main] INFO  i.v.w.f.b.n.s.NettyServerChannelActor - Netty server using EpollEventLoopGroup
15:34:27.968 [main] INFO  i.v.w.f.b.n.s.NettyServerChannelActor - Netty server using EpollEventLoopGroup 10
15:34:27.998 [main] INFO  i.v.w.f.b.n.s.NettyServerChannelActor - Netty server using EpollServerSocketChannel
15:34:28.076 [main] INFO  i.v.w.f.b.n.s.NettyServerChannelActor - Netty server server-request-response-channel actor started
15:39:37.522 [epollEventLoopGroup-3-1] DEBUG i.v.w.f.b.n.s.NettyInboundHandler - >>>>> NettyInboundHandler::channelActive(): 1 NAME: NettyInboundHandler#0:1
15:39:37.541 [epollEventLoopGroup-3-1] DEBUG i.v.w.f.b.n.s.NettyInboundHandler - >>>>> NettyInboundHandler::channelRead(): 1 NAME: NettyInboundHandler#0:1
15:39:37.557 [epollEventLoopGroup-3-1] DEBUG i.v.w.f.b.n.s.NettyInboundHandler - >>>>> NettyInboundHandler::respondWith(): 1 NAME: NettyInboundHandler#0:1 : CLOSE? false
15:39:37.562 [epollEventLoopGroup-3-1] DEBUG i.v.w.f.b.n.s.NettyInboundHandler - Reply sent
15:39:37.565 [epollEventLoopGroup-3-1] DEBUG i.v.w.f.b.n.s.NettyInboundHandler - >>>>> NettyInboundHandler::channelUnregistered(): 1 NAME: NettyInboundHandler#0:1
^C=========================
Stopping hello-world.
=========================

```

Unable to read properties. ????

**Comment by awsl-dbq** [comment]
I just copy https://github.com/vlingo/vlingo-xoom/blob/master/src/main/resources/vlingo-xoom.properties
to src/main/resource 
then compile it
It works well.

**Comment by VaughnVernon** [comment]
@awsl-dbq Thanks for reporting. It looks like @danilo-ambrosio updated the project to used vlingo-xoom but left out the properties file, or maybe the properties are now needed but weren't when he did the update to vlingo-xoom.

@danilo-ambrosio Can you please correct this in the project? Also I noticed that the vlingo-xoom dependency uses `${project.version}` but the other vlingo-* dependencies are explicit and behind quite a bit. Can you also fix that?

Thanks a bunch!

**Comment by danilo-ambrosio** [comment]
Sure! I'll check this out and solve it.

**Comment by danilo-ambrosio** [comment]
@awsl-dbq 
Thanks for the details. I've changed `vlingo-xoom` so, as of now, the properties file is no longer required.

Additionally, in regard to `vlingo-helloworld`, I've removed useless dependencies and improved the build settings so the package goal is running faster.

Could you please pull the changes on `vlingo-helloworld` and verify if everything's fine now?

Thanks in advance!

**Comment by awsl-dbq** [comment]
> @awsl-dbq
> Thanks for the details. I've changed `vlingo-xoom` so, as of now, the properties file is no longer required.
> 
> Additionally, in regard to `vlingo-helloworld`, I've removed useless dependencies and improved the build settings so the package goal is running faster.
> 
> Could you please pull the changes on `vlingo-helloworld` and verify if everything's fine now?
> 
> Thanks in advance!

@danilo-ambrosio  Hi, Thanks a lot. 
I git pull the `vlingo-xoom` `vlingo-heloworld`code . And recompile the `vlingo-helloworld`
It works as expected.
There still a little questions. The `readme.md` should also be updated. 
`target/vlingo-helloworld-withdeps.jar ` should update to `target/vlingo-helloworld.jar`
After compiled ,no jar named `vlingo-helloworld-withdeps.jar` but only `vlingo-helloworld.jar`  in targert .

**Comment by danilo-ambrosio** [comment]
> > @awsl-dbq
> > Thanks for the details. I've changed `vlingo-xoom` so, as of now, the properties file is no longer required.
> > Additionally, in regard to `vlingo-helloworld`, I've removed useless dependencies and improved the build settings so the package goal is running faster.
> > Could you please pull the changes on `vlingo-helloworld` and verify if everything's fine now?
> > Thanks in advance!
> 
> @danilo-ambrosio Hi, Thanks a lot.
> I git pull the `vlingo-xoom` `vlingo-heloworld`code . And recompile the `vlingo-helloworld`
> It works as expected.
> There still a little questions. The `readme.md` should also be updated.
> `target/vlingo-helloworld-withdeps.jar ` should update to `target/vlingo-helloworld.jar`
> After compiled ,no jar named `vlingo-helloworld-withdeps.jar` but only `vlingo-helloworld.jar` in targert .

Thanks for your quick reply @awsl-dbq . 
In regard to the new jar name, I actually pushed that change on README along with other fixes I mentioned before.
