### ISSUE TITLE
Cannot resolve io.vlingo:vlingo-http:1.3.4-SNAPSHOT

### ISSUE THREAD

**Issue by walkerx** [vlingo/vlingo-helloworld#8]
Cannot resolve io.vlingo:vlingo-http:1.3.4-SNAPSHOT

**Comment by VaughnVernon** [comment]
@walkerx Please see:

https://oss.jfrog.org/artifactory/oss-snapshot-local/io/vlingo/vlingo-http/1.3.4-SNAPSHOT/
